# baseURL = "https://example.edu"
languageCode = "en-us"
title = "Francesco Granella"
# theme = "avicenna"
googleAnalytics = "UA-159974102-1"
timeout=3000

[params]
  subtitle= "PhD Student"
  # interests="Environmental economics, political economics"
  cv_name= "CV_Apr2020.pdf"
  # blog="http://myblog.edu"

[[params.affilation]]
  name = "Bocconi University"
  position = "PhD student"
  contact = "[name].[lastname]@unibocconi.it"

[[params.affilation]]
  name = "RFF-CMCC European Insitute on Economics and the Environment"
  position = "Post-degree researcher"
  contact = "[name].[lastname]@eiee.org"

# [[params.social]]
#   name = "GitHub"
#   icon = "github"
#   url = "https://github.com/"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/"


# [[params.social]]
#   name = "LinkedIn"
#   icon = "linkedin"
#   url = "https://linkedin.com/in/"


# [[params.introduction.paragraph]]
#   text="""I am a PhD student in Public Policy & Administration at Bocconi University."""

[[params.introduction.paragraph]]
  text="""  

  """

[[params.wips]]
	[[params.wips.wip]]
		name = "*Air pollution and physical performance*"
		# description  = "descrip"
		# project_page = ""
		# code_link = ""
		# blog_link = ""
[[params.wips]]
	[[params.wips.wip]]
		name = "*Employment dynamics in the aftermath of urban floods*"
		# description  = "descrip"
		# project_page = ""
		# code_link = ""
		# blog_link = ""

[[params.wips]]
	[[params.wips.wip]]
		name = "*Is (campaign) money for nothing? The effects of the 2015 Brazilian ban on corporate contributions on procurement outcomes and other forms of campaign contributions.*  With Alexandros Cavgias"
		description  = "Presented at the 2020 Conference of the American Political Science Association"
		# project_page = ""
		# code_link = ""
		# blog_link = ""

[[params.wips]]
	[[params.wips.wip]]
		name = "*PATFIND: an algorithm for matching PATSTAT with firm-level data.*  With Elena Verdolini"
		# description  = "With Elena Verdolini"
		# project_page = ""
		# code_link = ""
		# blog_link = ""

[[params.wips]]
	[[params.wips.wip]]
		name = "*Pairwise speech distance in the U.S. Congress: A perspective on polarization*"
		description  = "Poster presented at the 5th International Conference on Computational Social Science, July 17-20 2019, Amsterdam (The Netherlands)"
		# project_page = ""
		# code_link = ""
		# blog_link = ""

[[params.wips]]
	[[params.wips.wip]]
		name = "*Environmental policy stringency and international collaboration in inventive activity. Evidence from the wind power sector*"
		description  = "Presented at the 7th Annual Conference of the Italian Association of Environmental and Resource Economists, 7-8 February 2019, Udine (Italy)"
		# project_page = ""
		# code_link = ""
		# blog_link = ""

[[params.wps]]

   [[params.wps.paper]]
     name = "COVID-19 lockdown only partially alleviates health impacts of air pollution in Northern Italy"
    authors = "__Francesco Granella__, Lara Aleluia Reis, Valentina Bosetti, Massimo Tavoni"
     # dest  = ""
     link = "https://osf.io/b38h2"
     # code_link = "https://thecoderepo.com"
     # blog_link = "https://myblogaboutit.com"
     # description = ""


# [[params.projects]]
# 	[[params.projects.project]]
# 		name = "Air pollution and physical performance"
# 		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		# project_page = "https://myprojecthomepage.com"
		# code_link = "https://coderepo.com"
		# blog_link = "https://ablogpost.com"

 # [[params._projects.project]]
	# 	name = "Integer eget aliquet nibh praesent tristique magna"
	# 	description  = ""
	# 	project_page = "https://myprojecthomepage.com"
	# 	code_link = ""
	# 	bloglink = "https://ablogpost.com"

# [[params.publications]]
# year="Preprint"

#    [[params.publications.paper]]
#      name = "Enim nunc faucibus a pellentesque sit amet porttitor"
#     authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
#      dest  = "Helga Zita Journal"
#      link = "https://mypaperishere.com"
#      code_link = "https://thecoderepo.com"
#      blog_link = "https://myblogaboutit.com"

#   [[params.publications.paper]]
#     name = "In cursus turpis massa tincidunt dui ut ornare lectus sit"
#     authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
#     dest  = "Meklit Katlego Conference"
#     link = "https://mypaperishere.com"
#     code_link = "https://thecoderepo.com"
#     blog_link = "https://myblogaboutit.com"

# [[params.publications]]
#   year="2019"

#   [[params.publications.paper]]
# 		name = "Feugiat sed lectus vestibulum mattis ullamcorper velit sed"
# 		authors = "Caroll Comes, __Hadi Sinaee__"
# 		dest  = "Udo Madhu Journal"
# 		link = "https://mypaperishere.com"
# 		code_link = "https://thecoderepo.com"
# 		blog_link = ""

#   [[params.publications.paper]]
# 		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
# 		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
# 		dest  = "Zorka Vita Conference"
# 		link = "https://mypaperishere.com"
# 		code_link = ""
# 		blog_link = "https://myblogaboutit.com"

#   [[params.publications.paper]]
# 		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
# 		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
# 		dest  = "Lena Randa Conference"
# 		link = "https://mypaperishere.com"
# 		code_link = ""
# 		blog_link = ""

#   [[params.publications.paper]]
# 		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
# 		authors = "__Hadi Sinaee__, Caroll Comes"
# 		dest  = "Thandeka Radhika Conference"
# 		link = ""
# 		code_link = ""
# 		blog_link = ""
